server:
  port: 8080

spring:
  application:
    name: ecommerce
  datasource:
#    url: jdbc:mariadb://localhost:3306/eCommerce?useSSL=false&serverTimezone=UTC
#    username: root
#    password: 12345678
#    driver-class-name: org.mariadb.jdbc.Driver
     url: jdbc:mysql://root:jSWABHtetITwhScxQyFCmIQGstLbUCIA@viaduct.proxy.rlwy.net:16471/railway
     username: root
     password: jSWABHtetITwhScxQyFCmIQGstLbUCIA
     driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  messages:
      basename: i18n/messages
      encoding: UTF-8
api:
  prefix: api/v1

jwt:
  expiration: 2592000
  secretKey: hfVj450p2BKXQ4Vy4Jtxf/lrUISk2UG45Yi6Uu2vecU=
payment:
  vnPay:
    url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    tmnCode: 58X4B4HP
    hashSecret: VRLDWNVWDNPCOEPBZUTWSEDQAGXJCNGZ
    returnUrl: http://localhost:8080/api/v1/payment/vnpay-callback
    version: 2.1.0
    command: pay
    order_type: other



